import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "../components/mode-toggle";
import {
  Facebook,
  Instagram,
  RectangleGogglesIcon,
  Twitch,
} from "lucide-react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="hidden md:block">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header className="max-w-[1400px] m-auto p-4">
              <nav className="flex items-center justify-center mt-4">
                <div className="flex items-center gap-[40px]">
                  <Link href="/">
                    <span>Booking</span>
                  </Link>
                  <Link href="/facilities">
                    <span>Facilities</span>
                  </Link>
                  <span>About Us</span>
                  <span>Location</span>
                  <span>Contact</span>
                </div>
                <div className="relative left-100 flex items-center gap-[10px]">
                  <ModeToggle />
                  <button className="text-[white] bg-[#24AB70] p-2 w-30 rounded-[20px]">
                    Login
                  </button>
                </div>
              </nav>
            </header>
            <main className="max-w-[1400px] m-auto p-4">{children}</main>
            <footer className="max-w-[1400px] m-auto p-4">
              <section className="flex items-baseline justify-between">
                <div className="flex flex-col items-start gap-[20px]">
                  <p className="w-60">
                    Lorem Ipsum is simply dummy text of the printing and
                    typesetting industry.
                  </p>
                  <div className="flex items-center gap-[10px]">
                    <Facebook />
                    <Instagram />
                    <Twitch />
                  </div>
                </div>
                <div className="flex flex-col items-start gap-[20px]">
                  <h1 className="text-[24px]">Home</h1>
                  <p>Booking</p>
                  <p>Facilities</p>
                  <p>Location</p>
                  <p>Contact</p>
                </div>
                <div className="flex flex-col items-start gap-[20px]">
                  <h1 className="text-[24px]">Help</h1>
                  <p>About Us</p>
                  <p>Help center</p>
                  <p>Privacy policy</p>
                  <p>FAQs</p>
                </div>
                <div className="flex flex-col items-start gap-[20px]">
                  <h1 className="text-[24px]">Get the app</h1>
                  <p>iOS app</p>
                  <p>Android app</p>
                </div>
              </section>
            </footer>
          </ThemeProvider>
        </div>


        <div className="block md:hidden min-h-screen flex flex-col">
          <div className="w-full p-4 flex justify-between items-center bg-white dark:bg-gray-900 shadow-md">
            <span className="font-bold text-xl text-gray-900 dark:text-white">
              Booking
            </span>
            <div className="flex items-center gap-2">
              <ModeToggle />
              <div className="space-y-1 cursor-pointer">
                <span className="block w-6 h-0.5 bg-current"></span>
                <span className="block w-6 h-0.5 bg-current"></span>
                <span className="block w-6 h-0.5 bg-current"></span>
              </div>
            </div>
          </div>

          <div className="bg-white dark:bg-gray-900 shadow-md">
            <div className="flex flex-col p-4 gap-4 text-gray-900 dark:text-white">
              <Link href="/">
                <div>Booking</div>
              </Link>
              <Link href="/facilities">
                <div>Facilities</div>
              </Link>
              <div>About Us</div>
              <div>Location</div>
              <div>Contact</div>
              <button className="bg-[#24AB70] text-white p-2 rounded-[20px] mt-2">
                Login
              </button>
            </div>
          </div>

          <main className="flex-1 p-4">{children}</main>

          <div className="p-4 bg-white dark:bg-gray-900 text-gray-900 dark:text-white">
            <div className="flex flex-col gap-6">
              <div className="flex flex-col gap-2">
                <p>
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry.
                </p>
                <div className="flex gap-2">
                  <Facebook />
                  <Instagram />
                  <Twitch />
                </div>
              </div>
              <div className="flex flex-col gap-2">
                <h1 className="text-lg font-bold">Home</h1>
                <p>Booking</p>
                <p>Facilities</p>
                <p>Location</p>
                <p>Contact</p>
              </div>
              <div className="flex flex-col gap-2">
                <h1 className="text-lg font-bold">Help</h1>
                <p>About Us</p>
                <p>Help center</p>
                <p>Privacy policy</p>
                <p>FAQs</p>
              </div>
              <div className="flex flex-col gap-2">
                <h1 className="text-lg font-bold">Get the app</h1>
                <p>iOS app</p>
                <p>Android app</p>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
